//
// Created by Sandeep Rana on 14/10/17.
// Copyright (c) 2017 DocNMe. All rights reserved.
//

import Foundation

class Loaders {
    static let listResults = ["ALK. PHOSPHTASE",
                       "AMH (ANTI MULLERIAN HORMONE)",
                       "ANDROSTENEDIONE",
                       "ANTI BETA 2 GLYCOPROTEIN",
                       "ANTI DS DNA",
                       "ANTICARDIOLIPIN AB IGG /IGM",
                       "BETA HCG",
                       "BILIRUBIN",
                       "BLOOD SUGAR FASTING",
                       "BLOOD SUGAR PP",
                       "BLOOD SUGAR Random",
                       "Blood Grouping and Rh Typing",
                       "CBC",
                       "CREATININ",
                       "CUE",
                       "Double Marker",
                       "ECG",
                       "ESTROGEN",
                       "FSH",
                       "Free T3",
                       "Free T4",
                       "GCT",
                       "HCV",
                       "HIV",
                       "HPV",
                       "Hb",
                       "HbA1C",
                       "HbSAg",
                       "Hormonal tests",
                       "Iron",
                       "LDH",
                       "LH",
                       "LUPUS ANTICOAGULANT",
                       "Liver Function Test (LFT)",
                       "OGTT",
                       "PAPP - A",
                       "PH, Urine",
                       "PREIN S",
                       "PROGESTERONE",
                       "PROLACTIN",
                       "PROTEIN C",
                       "Physician opinion",
                       "Rh Antibody (Anti-D)",
                       "SGOT",
                       "SGPT",
                       "SHBG",
                       "Semen Analysis",
                       "T3",
                       "T4",
                       "TESTOSTERONE",
                       "TPO",
                       "TSH",
                       "Triple Marker",
                       "UREA",
                       "URINE C/S",
                       "URINE R/M",
                       "VDRL",
                       "Vitamin B12",
                       "Vitamin D"];
}
